language: python
python: 3.7

env:
  global:
    # doctr generated secure variable for documentation upload
    - secure: "T3qltv0RCsGWwlRvRkhtiPTa5QdvK58XJ4Ah7KGRo1w+5gny4fwywKdfBa7gLuGCsI5Y8wJUsbh8LOg6O2PdOybkQQc+n81lp2lo641oe2zZJrHBu3KjgX/Tnr7jIRNOjtxGy9wHJGNVKZ92ObhBsplSgWXjfEqk/AytDh075d3SdY8adMNNqf/JAHjS+gmKNz+F4XlE+UfqD8Y5Tkk5YzE0ELXckYtO4mjoHEL2NpZrvD+cJ7bkFqCbtZCyJQNsqWalsKwoVUdO+ClcKmfqgPlSrhUsrLziN96RerQgK3pHMz4G7EqRiNsdCa9aLQgW/2r7JEEpf0AVqD3bfXYaJ60RURVXEJ4UG86jp94oMdmfvrGyy2mY3uhcJDsrzZuniwYoYnsuNzW+h/zwbzYFuGFGwPcAPSRb09qwHBK4U5Rb522EU9otIbRSXdc6wh7K3lvGtAvlhDVBBcc0095qbrdA1rpiMKDW635tuXiwBT2Ad1cc+Yv6iPWn1gV2//E4SPz18YV6JUrr5/lPdDDth8/WxIfgECWlhIr+eDpGW8vcRWZwAAdH1/I0F+0kPdvIbfoqXg0UgTE8bi3BHyRhrtkp8zcmOd0qH7vPDyJU3z6pG3l5SJy6pZsrXwAcG/LT83hW8blCuQVqmqwZD/50yIFr0anJizCYyGdkVEF71Po="
    - TWINCAT_STYLE_EXCLUDE=
    # If using a custom version of the CI helpers, change the following in
    # addition to the `import` block elow:
    # - CI_HELPER_URL=https://github.com/klauer/pcds-ci-helpers
    # - CI_HELPER_BRANCH=twincat_shared_configs

# Uncomment this block if you would like to make a test an allowed failure
jobs:
  allow_failures:
    - name: "Style Check"
    - name: "Pre-commit Checks"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/standard.yml

# If not using the standard-python-conda above please uncomment the required
# (language, os, dist and stages) and optional (import statements) entries from
# the blocks below.
#
#language: python
#os: linux
#dist: xenial
#
#stages:
#  - build
#  - test
#  - name: deploy
#    if: (branch = master OR tag IS present) AND type != pull_request
#
#import:
#  # Build stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/setup.yml
#  # Test stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/docs-build.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/pragmalint.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/pre-commit.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/style.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/summary.yml
#  # Deploy stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/doctr-upload.yml
