<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.6">
  <POU Name="FB_PfeifferTurboPump" Id="{8a094e05-8b3e-4241-abfb-693b3ec2b80c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PfeifferTurboPump EXTENDS FB_TurboPump
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>